### PR TITLE
fix: Handle Redis connection errors gracefully instead of panicking

### LINKED ISSUE #109: trino-lb is stuck after redis master shuts down
We are experiencing crashes in trino-lb on Kubernetes version 1.32.5 with a trino-lb HA setup and an underlying Redis instance, which can only be resolved by restarting the container or pod.
It all starts with the Redis master stopping. For an unknown reason, it receives a SIGTERM signal. As a result, the master shuts down. This leads to an error in trino-lb: "Redis error" and "broken pipe."  
The trino-lb pods behave differently at that point in time. We have three different pods running in HA mode.

**Example 1:**
Two pods survive the outage; they do not log anything during that time, but after being restarted by the liveness probe, they become available again and start logging normally.
There is one pod that crashes. A new pod is started to replace it, and it starts logging immediately, even during the outage period.

**Example 2:**
Only one Pod is stuck. The other two have a short outage period while master is switching and start logging again.

This behavior was observed in version 0.4.1 and 0.6.0. Sometimes pods die for a few seconds and recover while others are not logging for several minutes to Hours. I have attached the logs below

--- Logs ---

Example 1:
redis master container sentinel:
```
1:signal-handler (1775586999) Received SIGTERM scheduling shutdown..."
"1:X 07 Apr 2026 18:36:39.181 * User requested shutdown..."
"1:X 07 Apr 2026 18:36:39.181 # Sentinel is now ready to exit, bye bye..."

# 5.5 min downtime no Restart or new Pod in k8s. Redis starts again.
"1:X 07 Apr 2026 18:42:08.171 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo"
```

redis master container redis:
```
"1:signal-handler (1775586999) Received SIGTERM scheduling shutdown..."
"1:M 07 Apr 2026 18:36:39.248 * User requested shutdown..."
"1:M 07 Apr 2026 18:36:39.248 * Waiting for replicas before shutting down."
"1:M 07 Apr 2026 18:36:39.751 * 2 of 2 replicas are in sync when shutting down."
"1:M 07 Apr 2026 18:36:39.751 * Saving the final RDB snapshot before exiting."
"1:M 07 Apr 2026 18:36:40.746 * DB saved on disk"
"1:M 07 Apr 2026 18:36:40.746 # Redis is now ready to exit, bye bye..."

# same pause in redis container
"1:C 07 Apr 2026 18:42:07.975 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo"
```

redis slaves:
normal missing master sync and voting. Registering new slave after old master comes back

trino-lb 1 survivor :
```
# normal logging
"2026-04-07T18:36:38.911154Z INFO Scaler::reconcile: trino_lb::scaling:All cluster groups reconciled"
"2026-04-07T18:36:38.911162Z  INFO trino_lb::scaling: Scaler: reconciled"
# error
"2026-04-07T18:36:40.759009Z ERROR trino_lb::scaling: Scaler: reconciled failed error=ReadCurrentClusterStateFromPersistence { source: RedisError { source: GetClusterState { source: broken pipe } }, cluster: \"default-1\" }"
# pause of about 1,5h
"2026-04-07T20:07:19.282352Z INFO trino_lb::http_server: Shutting down gracefully"
"2026-04-07T20:07:19.282373Z INFO trino_lb::http_server: Waiting for all connections to close connections=3"
"2026-04-07T20:07:19.282798Z WARN h2::proto::streams::recv: recv_reset; remotely-reset pending-accept streams reached limit (20)"
"2026-04-07T20:07:19.285431Z INFO Fetching current query counters: trino_lb::maintenance::query_count_fetcher: QueryCountFetcher: Did not update query counters, as there already was a update Ok(11.916424387s) ago."
"2026-04-07T20:07:19.285436Z INFO Checking for leftover queued queries:delete_queued_queries_not_accessed_after{not_accessed_after=SystemTime { tv_sec: 1775586711, tv_nsec: 391978017 }}:delete_queued_queries_not_accessed_after_for_cluster_group{cluster_group=\"default\" not_accessed_after=SystemTime { tv_sec: 1775586711, tv_nsec: 391978017 }}: trino_lb_persistence::redis: Deleted all queries that were not accessed after cluster_group=\"default\" removed=0 not_accessed_after=SystemTime { tv_sec: 1775586711, tv_nsec: 391978017 }"
"2026-04-07T20:07:19.285466Z INFO Scaler::reconcile:Scaler::reconcile_cluster_group{cluster_group=\"default\"}: trino_lb::scaling: Current cluster states current_state={\"default-1\": Ready}"
"2026-04-07T20:07:19.285497Z INFO Checking for leftover queued queries:delete_queued_queries_not_accessed_after{not_accessed_after=SystemTime { tv_sec: 1775586711, tv_nsec: 391978017 }}:delete_queued_queries_not_accessed_after_for_cluster_group{cluster_group=\"fallback\" not_accessed_after=SystemTime { tv_sec: 1775586711, tv_nsec: 391978017 }: trino_lb_persistence::redis: Deleted all queries that were not accessed after cluster_group=\"fallback\" removed=0 not_accessed_afterSystemTime { tv_sec: 1775586711, tv_nsec: 391978017 }"
"2026-04-07T20:07:19.285809Z INFO Fetching current query counters: trino_lb::maintenance::query_count_fetcher QueryCountFetcher: Did not update query counters, as there already was a update Ok(11.916808115s) ago."
"2026-04-07T20:07:19.285997Z INFO Checking for leftover queued queries:delete_queued_queries_not_accessed_after{not_accessed_after=SystemTime { tv_sec: 1775592139, tv_nsec: 285523953 }}:delete_queued_queries_not_accessed_after_for_cluster_group{cluster_group=\"default\" not_accessed_after=SystemTime { tv_sec: 1775592139, tv_nsec: 285523953 }}: trino_lb_persistence::redis: Deleted all queries that were not accessed after cluster_group=\"default\" removed=0 not_accessed_after=SystemTime { tv_sec: 1775592139, tv_nsec: 285523953 }"
"2026-04-07T20:07:19.286024Z INFO Checking for leftover queued queries:delete_queued_queries_not_accessed_after{not_accessed_after=SystemTime { tv_sec: 1775592139, tv_nsec: 285523953 }}:delete_queued_queries_not_accessed_after_for_cluster_group{cluster_group=\"fallback\" not_accessed_after=SystemTime { tv_sec: 1775592139, tv_nsec: 285523953 }}: trino_lb_persistence::redis: Deleted all queries that were not accessed after cluster_group=\"fallback\" removed=0 mnot_accessed_after=SystemTime { tv_sec: 1775592139, tv_nsec: 285523953 }"
```

trino-lb 2 survivor:
```
"2026-04-07T18:36:39.300019Z INFO Scaler::reconcile:Scaler::reconcile_cluster_group{cluster_group=\"default\"}: trino_lb::scaling: Current cluster states current_states={\"default-1\": Ready}"
# error
"2026-04-07T18:36:40.758889Z ERROR trino_lb::scaling: Scaler: reconciled failed error=SetCurrentClusterStateInPersistence { source: RedisError { source: SetClusterState { source: broken pipe } }, cluster: \"default-1\" }"
"2026-04-07T18:36:40.758885Z WARN trino_lb::http_server::v1::statement: Error while processing request error=FindBestClusterForClusterGroup { source: ReadCurrentClusterStateForClusterGroupFromPersistence { source: RedisError { source: GetClusterState { source: broken pipe } }, cluster_group: \"default\" }, cluster_group: \"default\" }"
# pause of 1,5h
"2026-04-07T19:58:58.249779Z INFO trino_lb::http_server: Shutting down gracefully"
"2026-04-07T19:58:58.249803Z INFO trino_lb::http_server: Waiting for all connections to close connections=3"
"2026-04-07T19:58:58.250345Z WARN h2::proto::streams::recv: recv_reset; remotely-reset pending-accept streams reached limit (20)"
"2026-04-07T19:58:58.252926Z INFO Scaler::reconcile:Scaler::reconcile_cluster_group{cluster_group=\"default\"}: trino_lb::scaling: Current cluster states current_states={\"default-1\": Ready}"
```

trino-lb 3 crashed:
```
"2026-04-07T18:36:38.420641Z INFO Scaler::reconcile: trino_lb::scaling: All cluster groups reconciled"
"2026-04-07T18:36:38.420648Z INFO trino_lb::scaling: Scaler: reconciled"
# logs end
```

trino-lb 4 replace for 3:
#normal Startup and reconcile until 2026-05-07T20:02 where more than usual POST and GET requests are logged.

---

Example 2:

same as example 1 for most pods.
Logs of surviving and quickly recovering pod

```
"2026-04-10T22:06:47.262335Z INFO trino_lb::scaling: Scaler: reconciled"
"2026-04-10T22:06:48.170263Z INFO Scaler::reconcile:Scaler::reconcile_cluster_group{cluster_group=\"default\": trino_lb::scaling: Current cluster states current_states={\"default-1\": Ready}"
# new logs
"thread '<unnamed>' (48) panicked at /trino-lb/trino-lb-persistence/src/redis/mod.rs:431:14:",
"called `Result::unwrap()` on an `Err` value: broken pipe"
"note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"
"2026-04-10T22:06:50.573775Z ERROR trino_lb::scaling: Scaler: reconciled failed error=SetCurrentClusterStateInPersistence { source: RedisError { source: SetClusterState { source: broken pipe } }, cluster: \"default-1\" }"
"thread '<unnamed>' (19581) panicked at trino-lb/src/metrics.rs:147:82:"
"called `Option::unwrap()` on a `None` value"
"thread 'tokio-runtime-worker' (43) panicked at trino-lb/src/metrics.rs:149:26:"
"called `Result::unwrap()` on an `Err` value: Any { .. }"
"OpenTelemetry error occurred. poisoned lock: another task failed inside"
"OpenTelemetry error occurred. poisoned lock: another task failed inside"
"2026-04-10T22:07:00.010038Z ERROR trino_lb::scaling: Scaler: reconciled failed error=ReadCurrentClusterStateFromPersistence { source: RedisError { source: GetClusterState { source: broken pipe } }, cluster: \"default-1\" }"
"2026-04-10T22:07:00.467349Z INFO Scaler::reconcile:Scaler::reconcile_cluster_group{cluster_group=\"default\"}: trino_lb::scaling: Current cluster states current_states={\"default-1\": Ready}"
# normal logging continues
```

### PR DESCRIPTION
**Pull request by sbernauer**
Maybe fixes https://github.com/stackabletech/trino-lb/issues/109

When Redis goes down (e.g. master failover), a broken pipe error would cause `get_queued_query_count` to panic due to an `.unwrap()`, which then poisoned the RwLock used in metrics callbacks, cascading into further panics and leaving pods unresponsive until the liveness probe killed them.

- Replace `.unwrap()` with proper error propagation in `get_queued_query_count`
- Handle poisoned locks, closed channels, and panicked threads gracefully in both metrics callbacks

### CODE REVIEW

File: trino-lb-persistence/src/redis/mod.rs [hunk 1]
```diff
@@ -428,7 +434,7 @@ where
             .connection()
             .scard::<_, Option<u64>>(queued_query_set_name(cluster_group))
             .await
-            .unwrap()
+            .context(GetQueuedQueryCountSnafu { cluster_group })?
```
Comment (NickLarsenNZ) [inline trino-lb-persistence/src/redis/mod.rs:437]: A valuable lesson :D

File: trino-lb/src/metrics.rs [hunk 2]
```diff
@@ -183,24 +206,47 @@ impl Metrics {
...
+                                Ok(r) => r,
+                                Err(err) => {
+                                    error!(error = %err, "Failed to acquire write lock for cluster_counts_per_state metric");
+                                    return None;
+                                }
+                            };
+                            match receiver.blocking_recv() {
+                                Some(v) => Some(v),
+                                None => {
+                                    error!("cluster_counts_per_state metrics channel closed");
```
Comment (NickLarsenNZ) [inline trino-lb/src/metrics.rs:225]: Some of the strings could be interpolated (so if the metric name changes, then so does the error). Not sure how feasible that is, so totally optional right now.

**Review by NickLarsenNZ — APPROVED** [review]
LGTM

**Comment by sbernauer** [comment]
Kuttl tests passed :rocket:
